// Stub for GeminiService
class GeminiService {
  constructor(name, url) {
    this.name = name;
    this.url = url;
    console.log(`Stub ${this.name} service initialized for URL: ${this.url}`);
  }

  async initialize() {
    console.log(`Stub ${this.name} service: initialize method called.`);
  }

  async generateScript(strategy) {
    console.log(`Stub ${this.name} service: generateScript called with strategy:`, strategy);
    return `This is a dummy script generated by ${this.name} for topic: ${strategy.topic || 'unknown topic'}`;
  }

  async close() {
    console.log(`Stub ${this.name} service: close method called.`);
  }
}

module.exports = GeminiService;
